### PR TITLE
SECURESIGN-185 | Add tests to all pipelines

### PR DESCRIPTION
**Pull request by JasonPowr**
PR to add go unit tests to trillian

### CODE REVIEW

**Review by lance — APPROVED** [review]
/lgtm

**Comment by JasonPowr** [comment]
@lance While the unit tests are passing, we seem to be hitting a resource quota for pods and CPU

```
48m         Normal    ExceededResourceQuota    taskrun/trillian-logsigner-1-5-on-pull-request-g627r-build-container      TaskRun Pod exceeded available resources: pods "trillian-logsigner-1-5-on-p255b5b5634da9747369ef9f9b7bfd610-pod" is forbidden: exceeded quota: for-rhtas-deployments, requested: count/pods=1, used: count/pods=300, limited: count/pods=300
49m         Normal    ExceededResourceQuota    taskrun/trillian-logsigner-1-5-on-pull-request-g627r-build-container      TaskRun Pod exceeded available resources: pods "trillian-logsigner-1-5-on-p255b5b5634da9747369ef9f9b7bfd610-pod" is forbidden: exceeded quota: compute-build, requested: limits.cpu=9, used: limits.cpu=117, limited: limits.cpu=120
47m         Normal    ExceededResourceQuota    taskrun/trillian-logsigner-1-5-on-pull-request-g627r-build-container      TaskRun Pod exceeded available resources: pods "trillian-logsigner-1-5-on-p255b5b5634da9747369ef9f9b7bfd610-pod" is forbidden: exceeded quota: compute-build, requested: limits.cpu=9, used: limits.cpu=118, limited: limits.cpu=120
```

**Comment by JasonPowr** [comment]
Its happening for other components also 

```
2m28s       Normal    ExceededResourceQuota    taskrun/rekor-server-1-0-gamma-on-push-lhgnm-init                         TaskRun Pod exceeded available resources: pods "rekor-server-1-0-gamma-on-push-lhgnm-init-pod" is forbidden: exceeded quota: compute-build, requested: limits.cpu=1,requests.cpu=250m, used: limits.cpu=120,requests.cpu=11805m, limited: limits.cpu=120,requests.cpu=12
87s         Normal    ExceededResourceQuota    taskrun/rekor-server-1-0-gamma-on-push-lhgnm-init                         TaskRun Pod exceeded available resources: pods "rekor-server-1-0-gamma-on-push-lhgnm-init-pod" is forbidden: exceeded quota: for-rhtas-deployments, requested: count/pods=1, used: count/pods=300, limited: count/pods=300
27s         Normal    ExceededResourceQuota    taskrun/rekor-server-1-0-gamma-on-push-lhgnm-init                         TaskRun Pod exceeded available resources: pods "rekor-server-1-0-gamma-on-push-lhgnm-init-pod" is forbidden: exceeded quota: compute-build, requested: requests.cpu=250m, used: requests.cpu=11871m, limited: requests.cpu=12
```

**Comment by JasonPowr** [comment]
A quota of 300 pods, seems like a lot as it is, is there a way we can stop the pods from the old workspaces ?

**Pull request merged**
