### PR TITLE
wip: verify unit tests are working

### PR DESCRIPTION
**Pull request by lcarva**

### CODE REVIEW

**Comment by lcarva** [comment]
Unit test Task output looks sus:

```
STEP-RUN-TESTS

go: downloading github.com/grpc-ecosystem/go-grpc-middleware v1.4.0
go: downloading github.com/prometheus/client_golang v1.18.0
go: downloading go.etcd.io/etcd/client/v3 v3.5.11
go: downloading golang.org/x/sync v0.6.0
go: downloading google.golang.org/grpc v1.61.0
go: downloading k8s.io/klog/v2 v2.120.1
go: downloading google.golang.org/genproto v0.0.0-20240102182953-50ed04b92917
go: downloading google.golang.org/protobuf v1.32.0
go: downloading github.com/golang/mock v1.6.0
go: downloading golang.org/x/crypto v0.18.0
go: downloading github.com/letsencrypt/pkcs11key/v4 v4.0.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/google/go-cmp v0.6.0
go: downloading github.com/transparency-dev/merkle v0.0.2
go: downloading github.com/apache/beam/sdks/v2 v2.0.0-20240131192626-89d1c06e1eab
go: downloading github.com/apache/beam v2.2.1-0.20240131192626-89d1c06e1eab+incompatible
go: downloading contrib.go.opencensus.io/exporter/stackdriver v0.13.14
go: downloading go.opencensus.io v0.24.0
go: downloading github.com/prometheus/client_model v0.5.0
go: downloading github.com/cockroachdb/cockroach-go/v2 v2.3.6
go: downloading google.golang.org/genproto/googleapis/rpc v0.0.0-20240116215550-a9fa1716bcac
go: downloading bitbucket.org/creachadair/shell v0.0.8
go: downloading github.com/google/btree v1.1.2
go: downloading github.com/lib/pq v1.10.9
go: downloading github.com/go-sql-driver/mysql v1.7.1
go: downloading golang.org/x/sys v0.16.0
go: downloading cloud.google.com/go/spanner v1.55.0
go: downloading google.golang.org/api v0.160.0
go: downloading cloud.google.com/go v0.111.0
go: downloading go.etcd.io/etcd/server/v3 v3.5.11
go: downloading github.com/fullstorydev/grpcurl v1.8.9
go: downloading github.com/google/go-licenses v1.6.0
go: downloading github.com/pseudomuto/protoc-gen-doc v1.5.1
go: downloading go.etcd.io/etcd/etcdctl/v3 v3.5.11
go: downloading go.etcd.io/etcd/v3 v3.5.11
go: downloading golang.org/x/tools v0.17.0
go: downloading google.golang.org/grpc/cmd/protoc-gen-go-grpc v1.3.0
go: downloading google.golang.org/genproto/googleapis/api v0.0.0-20240102182953-50ed04b92917
go: downloading github.com/go-redis/redis v6.15.9+incompatible
go: downloading go.etcd.io/etcd/api/v3 v3.5.11
go: downloading go.etcd.io/etcd/client/pkg/v3 v3.5.11
go: downloading go.uber.org/zap v1.26.0
go: downloading github.com/prometheus/common v0.45.0
go: downloading github.com/go-logr/logr v1.4.1
go: downloading golang.org/x/net v0.20.0
go: downloading github.com/golang/protobuf v1.5.3
go: downloading github.com/miekg/pkcs11 v1.1.1
go: downloading golang.org/x/exp v0.0.0-20231006140011-7918f672742d
go: downloading github.com/google/uuid v1.5.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.2.0
go: downloading github.com/prometheus/procfs v0.12.0
go: downloading github.com/gofrs/flock v0.8.1
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading cloud.google.com/go/compute/metadata v0.2.3
go: downloading cloud.google.com/go/monitoring v1.17.0
go: downloading cloud.google.com/go/trace v1.10.4
go: downloading cloud.google.com/go/compute v1.23.3
go: downloading github.com/census-instrumentation/opencensus-proto v0.4.1
go: downloading github.com/prometheus/prometheus v0.47.2
go: downloading golang.org/x/oauth2 v0.16.0
go: downloading github.com/jackc/pgx/v4 v4.18.1
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading github.com/googleapis/gax-go/v2 v2.12.0
go: downloading github.com/json-iterator/go v1.1.12
go: downloading golang.org/x/xerrors v0.0.0-20231012003039-104605ab7028
go: downloading cloud.google.com/go/iam v1.1.5
go: downloading cloud.google.com/go/longrunning v0.5.4
go: downloading golang.org/x/mod v0.14.0
go: downloading github.com/bgentry/speakeasy v0.1.0
go: downloading github.com/dustin/go-humanize v1.0.1
go: downloading github.com/olekukonko/tablewriter v0.0.5
go: downloading github.com/spf13/cobra v1.8.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading go.etcd.io/etcd/etcdutl/v3 v3.5.11
go: downloading go.etcd.io/etcd/pkg/v3 v3.5.11
go: downloading golang.org/x/time v0.5.0
go: downloading gopkg.in/cheggaaa/pb.v1 v1.0.28
go: downloading github.com/pseudomuto/protokit v0.2.0
go: downloading github.com/jhump/protoreflect v1.15.3
go: downloading github.com/otiai10/copy v1.6.0
go: downloading golang.org/x/text v0.14.0
go: downloading go.etcd.io/etcd/client/v2 v2.305.11
go: downloading go.etcd.io/etcd/tests/v3 v3.5.11
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/coreos/go-semver v0.3.1
go: downloading github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
go: downloading github.com/grpc-ecosystem/grpc-gateway v1.16.0
go: downloading github.com/soheilhy/cmux v0.1.5
go: downloading github.com/tmc/grpc-websocket-proxy v0.0.0-20220101234140-673ab2c3ae75
go: downloading go.etcd.io/bbolt v1.3.8
go: downloading go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.47.0
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.20.0
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.20.0
go: downloading go.opentelemetry.io/otel v1.22.0
go: downloading go.opentelemetry.io/otel/sdk v1.20.0
go: downloading go.uber.org/multierr v1.11.0
go: downloading gopkg.in/natefinch/lumberjack.v2 v2.2.1
go: downloading sigs.k8s.io/yaml v1.4.0
go: downloading github.com/coreos/go-systemd/v22 v22.5.0
go: downloading github.com/matttproud/golang_protobuf_extensions/v2 v2.0.0
go: downloading gopkg.in/retry.v1 v1.0.3
go: downloading cloud.google.com/go/storage v1.36.0
go: downloading github.com/jackc/pgconn v1.14.1
go: downloading github.com/jackc/pgio v1.0.0
go: downloading github.com/jackc/pgproto3/v2 v2.3.2
go: downloading github.com/jackc/pgtype v1.14.0
go: downloading go.opentelemetry.io/otel/trace v1.22.0
go: downloading google.golang.org/appengine v1.6.8
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading github.com/envoyproxy/go-control-plane v0.11.1
go: downloading github.com/urfave/cli v1.22.14
go: downloading github.com/mattn/go-runewidth v0.0.13
go: downloading github.com/inconshreveable/mousetrap v1.1.0
go: downloading go.etcd.io/etcd/raft/v3 v3.5.11
go: downloading github.com/Masterminds/sprig v2.22.0+incompatible
go: downloading github.com/mwitkow/go-proto-validators v0.2.0
go: downloading github.com/bufbuild/protocompile v0.6.0
go: downloading github.com/google/licenseclassifier v0.0.0-20210722185704-3043a050f148
go: downloading gopkg.in/src-d/go-git.v4 v4.13.1
go: downloading github.com/gorilla/websocket v1.5.0
go: downloading github.com/sirupsen/logrus v1.9.3
go: downloading github.com/xiang90/probing v0.0.0-20221125231312-a49e3df8f510
go: downloading github.com/jonboulle/clockwork v0.4.0
go: downloading go.opentelemetry.io/otel/metric v1.22.0
go: downloading go.opentelemetry.io/proto/otlp v1.0.0
go: downloading go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.47.0
go: downloading github.com/docker/docker v24.0.7+incompatible
go: downloading github.com/aws/aws-sdk-go v1.46.4
go: downloading github.com/jackc/chunkreader/v2 v2.0.1
go: downloading github.com/jackc/pgpassfile v1.0.0
go: downloading github.com/jackc/pgservicefile v0.0.0-20221227161230-091c0ba34f0a
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.3
go: downloading github.com/envoyproxy/protoc-gen-validate v1.0.2
go: downloading github.com/rivo/uniseg v0.4.4
go: downloading github.com/cncf/xds/go v0.0.0-20231109132714-523115ebc101
go: downloading github.com/cncf/udpa/go v0.0.0-20220112060539-c52dc94e7fbe
go: downloading github.com/Masterminds/goutils v1.1.1
go: downloading github.com/Masterminds/semver v1.5.0
go: downloading github.com/huandu/xstrings v1.2.0
go: downloading github.com/imdario/mergo v0.3.16
go: downloading github.com/mitchellh/copystructure v1.0.0
go: downloading github.com/golang-jwt/jwt/v4 v4.5.0
go: downloading github.com/cenkalti/backoff/v4 v4.2.1
go: downloading github.com/go-logr/stdr v1.2.2
go: downloading github.com/google/s2a-go v0.1.7
go: downloading github.com/googleapis/enterprise-certificate-proxy v0.3.2
go: downloading github.com/grpc-ecosystem/grpc-gateway/v2 v2.18.0
go: downloading github.com/felixge/httpsnoop v1.0.4
go: downloading github.com/sergi/go-diff v1.3.1
go: downloading gopkg.in/src-d/go-billy.v4 v4.3.2
go: downloading cloud.google.com/go/profiler v0.4.0
go: downloading github.com/russross/blackfriday/v2 v2.1.0
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/docker/go-units v0.5.0
go: downloading github.com/opencontainers/image-spec v1.1.0-rc5
go: downloading github.com/docker/distribution v2.8.3+incompatible
go: downloading github.com/opencontainers/go-digest v1.0.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/mitchellh/reflectwalk v1.0.1
go: downloading github.com/emirpasic/gods v1.18.1
go: downloading github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
go: downloading github.com/google/pprof v0.0.0-20231023181126-ff6d637d2a7b
go: downloading github.com/Microsoft/go-winio v0.6.1
go: downloading github.com/src-d/gcfg v1.4.0
go: downloading github.com/kevinburke/ssh_config v0.0.0-20190725054713-01f96b0aa0cd
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/xanzy/ssh-agent v0.3.3
go: downloading gopkg.in/warnings.v0 v0.1.2
go: downloading github.com/distribution/reference v0.5.0
go: downloading github.com/jmespath/go-jmespath v0.4.0
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
?   	github.com/google/trillian	[no test files]
```

It spends a lot of time fetching dependencies but then claims that there are no tests files. When I run the same command locally, quite a few tests are executed:

```
🐚 go test -count=1 $(go list ./... | grep -v /storage/ | grep -v /client/ )
?       github.com/google/trillian      [no test files]
?       github.com/google/trillian/cmd/deletetree       [no test files]
?       github.com/google/trillian/cmd/internal/serverutil      [no test files]
?       github.com/google/trillian/cmd/trillian_log_server      [no test files]
?       github.com/google/trillian/cmd/trillian_log_signer      [no test files]
ok      github.com/google/trillian/client       0.008s
ok      github.com/google/trillian/cmd  0.002s
?       github.com/google/trillian/crypto/keys/pkcs11   [no test files]
?       github.com/google/trillian/crypto/keys/testonly [no test files]
?       github.com/google/trillian/crypto/keyspb        [no test files]
?       github.com/google/trillian/docs/claimantmodel/experimental/cmd/render   [no test files]
?       github.com/google/trillian/docs/merkletree/treetex      [no test files]
?       github.com/google/trillian/experimental/batchmap/cmd/build      [no test files]
?       github.com/google/trillian/experimental/batchmap/cmd/verify     [no test files]
?       github.com/google/trillian/extension    [no test files]
?       github.com/google/trillian/integration/storagetest      [no test files]
?       github.com/google/trillian/monitoring/opencensus        [no test files]
?       github.com/google/trillian/monitoring/testonly  [no test files]
?       github.com/google/trillian/quota/etcd   [no test files]
?       github.com/google/trillian/quota/etcd/quotapb   [no test files]
?       github.com/google/trillian/quota/etcd/storagepb [no test files]
?       github.com/google/trillian/quota/redis/redisqm  [no test files]
?       github.com/google/trillian/quota/redis/redistb  [no test files]
ok      github.com/google/trillian/cmd/createtree       4.013s
ok      github.com/google/trillian/cmd/updatetree       0.009s
ok      github.com/google/trillian/crypto/keys  0.004s
ok      github.com/google/trillian/crypto/keys/der      0.004s
ok      github.com/google/trillian/crypto/keys/pem      0.007s
ok      github.com/google/trillian/docs/claimantmodel/experimental/cmd/render/internal  0.002s
ok      github.com/google/trillian/experimental/batchmap        0.651s
?       github.com/google/trillian/testonly     [no test files]
?       github.com/google/trillian/testonly/integration [no test files]
?       github.com/google/trillian/testonly/integration/etcd    [no test files]
?       github.com/google/trillian/testonly/mdm [no test files]
?       github.com/google/trillian/testonly/mdm/mdmtest [no test files]
?       github.com/google/trillian/testonly/tmock       [no test files]
?       github.com/google/trillian/testonly/setup       [no test files]
?       github.com/google/trillian/types/internal/tls   [no test files]
?       github.com/google/trillian/util [no test files]
?       github.com/google/trillian/util/election2       [no test files]
ok      github.com/google/trillian/integration  10.395s
ok      github.com/google/trillian/integration/admin    0.008s
ok      github.com/google/trillian/integration/format   0.775s
ok      github.com/google/trillian/integration/quota    0.016s
ok      github.com/google/trillian/log  3.824s
ok      github.com/google/trillian/merkle/coniks        0.004s
ok      github.com/google/trillian/merkle/smt   1.709s
ok      github.com/google/trillian/merkle/smt/node      0.002s
ok      github.com/google/trillian/monitoring   0.003s
ok      github.com/google/trillian/monitoring/prometheus        0.004s
ok      github.com/google/trillian/quota        0.002s
ok      github.com/google/trillian/quota/cacheqm        0.004s
ok      github.com/google/trillian/quota/crdbqm 27.095s
ok      github.com/google/trillian/quota/etcd/etcdqm    0.961s
ok      github.com/google/trillian/quota/etcd/quotaapi  2.998s
ok      github.com/google/trillian/quota/etcd/storage   0.641s
ok      github.com/google/trillian/quota/mysqlqm        0.004s
ok      github.com/google/trillian/server       0.073s
ok      github.com/google/trillian/server/admin 0.007s
ok      github.com/google/trillian/server/errors        0.007s
ok      github.com/google/trillian/server/interceptor   1.009s
ok      github.com/google/trillian/storage      0.005s
ok      github.com/google/trillian/testonly/flagsaver   0.002s
ok      github.com/google/trillian/testonly/matchers    0.004s
ok      github.com/google/trillian/trees        0.006s
ok      github.com/google/trillian/types        0.005s
ok      github.com/google/trillian/util/clock   1.403s
ok      github.com/google/trillian/util/election        2.011s
ok      github.com/google/trillian/util/election2/etcd  2.573s
ok      github.com/google/trillian/util/election2/testonly      1.406s
```

**Comment by JasonPowr** [comment]
Closing this pls re-open if it is a mistake

**Pull request closed without merging**
