### PR TITLE
Update Trillian to v1.6.1

### PR DESCRIPTION
**Pull request by JasonPowr**
Update Trillian to v1.6.1

### CODE REVIEW

**Comment by lance** [comment]
@JasonPowr I think cachi2 may be failing because we're using go 1.22 now with these updates.

**Comment by JasonPowr** [comment]
@lance I think that may have just been an intermittent issue, prefetch seems to be passing now and it was before

**Comment by JasonPowr** [comment]
Closing this and opening a new one as there seems to be a lot of conflicts now

**Pull request closed without merging**
