### PR TITLE
feat: add image for serving trillian CLI binaries

### PR DESCRIPTION
**Pull request by lance**
Used by the operator for serving binaries via HTTP. Fixes SECURESIGN-1223.

### CODE REVIEW

**Comment by tommyd450** [comment]
@lance We should probably move this to our own Securesign Quay Repository. This looks fine to merge now but we should move it either now or later.

**Comment by lance** [comment]
@tommyd450 what do I need to do to move it?

**Comment by lance** [comment]
Closing this in favor of https://github.com/securesign/cosign/pull/227

**Pull request closed without merging**
