### PR TITLE
[SECURESIGN-171] Minimising builds

### PR DESCRIPTION
**Pull request by tommyd450**
Apart of [SECURESIGN-171](https://issues.redhat.com//browse/SECURESIGN-171), an attempt to lower how many rhtap builds  are running in order to keep our workspace available for required builds for dev work etc.

### CODE REVIEW

**Comment by Gregory-Pereira** [comment]
As lance suggested this should be based against `redhat-v1.5`. This current branch, `redhat-v1.5.2` represents the beta release, and we have already downgraded to standard pipelines.

**Comment by lance** [comment]
@tommyd450 can you and @Gregory-Pereira work together to get these changes applied to the current working branch?

**Comment by Gregory-Pereira** [comment]
@lance ack, will do

**Comment by Gregory-Pereira** [comment]
Closing as we have reverted beta branch to standard pipelines.

**Pull request closed without merging**
