### PR TITLE
chore: prefetch dependencies and hermetic builds

### PR DESCRIPTION
**Pull request by lance**
This change configures prefetched dependencies and hermetic builds for createtree and updatetree builds.

### CODE REVIEW

**Comment by JasonPowr** [comment]
@lance EC seems to be complaining about updateTree and createTree not being build with hermetic, source and prefetch even though looking at the build pipelines, they are...

Id say its the snapshot deadlock issue here

**Comment by lance** [comment]
@JasonPowr I'll merge and see how it goes in Konflux - and adjust as needed.

**Pull request merged**
