### PR TITLE
Trillian enterprise contracts

### PR DESCRIPTION
**Pull request by tommyd450**
Some of the changes required for the enterprise contracts. More changes will follow as I make my way through the documentation and test how it works via my fork.

### CODE REVIEW

**Comment by tommyd450** [comment]
@lance These should be okay the only thing they are missing are the dockerfile labels which are already present on main and midstream-v*, I am still having issues with using the script. If you could run the sync these changes should work.

**Review by lance — APPROVED** [review]
/lgtm

**Pull request merged**
